# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  'exec-and-forget borders'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changesIue#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak|colemak)
# See I	
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal  =   8
    inner.vertical    =   8
    outer.left        =   4
    outer.bottom      =   4
    outer.top         =   3
    outer.right       =   4

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands



    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace

    shift-0           = 'workspace 0'
    shift-1           = 'workspace 1'
    shift-2           = 'workspace 2'
    shift-3           = 'workspace 3'
    shift-4           = 'workspace 4'
    shift-5           = 'workspace 5'
    shift-6           = 'workspace 6'
    shift-7           = 'workspace 7'
    shift-8           = 'workspace 8'
    shift-9           = 'workspace 9'

    # First row
    # cmd-q             =     'workspace Q'                                             
    # cmd-w             =     'workspace C'                                                                                      
    # cmd-e             =     'workspace O'                                               
    # cmd-r             =     'workspace P'
    # cmd-t = 'workspace W'
    # cmd-y             =     'workspace J'
    # cmd-u             =     'workspace M'                                             # attributed to moving to workspace
    # cmd-i             =     'workspace D'
    # cmd-o             =     'workspace deadKey'
    # cmd-p             =     'workspace Y'
    
    # Second row
    # cmd-a             =     'workspace A'
    # cmd-s = 'workspace S'                                               # attributed to resizing
    # cmd-d             =     'workspace E'
    # cmd-f             =     'workspace N'
    # cmd-g             =     'workspace F'
    # cmd-h           =     'workspace L'
    # cmd-j           =     'workspace R'
    # cmd-k           =     'workspace T'
    # cmd-l           =     'workspace I'
    # cmd-semicolon     =     'workspace U'

    # Third row
    # cmd-z             =     'workspace Z'
    # cmd-x             =     'workspace X'
    # cmd-c           =     'workspace -'
    # cmd-v             =     'workspace V'
    # cmd-b             =     'workspace B'
    # cmd-n           =     'workspace .'                                               # attributed to back-and-forth
    # cmd-m             =     'workspace H'
    # cmd-comma         =     'workspace G'
    # cmd-period      =     'workspace ,'
    # cmd-slash         =     'workspace K'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    # cmd-shift-0           = 'move-node-to-workspace 0'
    # cmd-shift-1           = 'move-node-to-workspace 1'
    # cmd-shift-2           = 'move-node-to-workspace 2'
    # cmd-shift-3           = 'move-node-to-workspace 3'
    # cmd-shift-4           = 'move-node-to-workspace 4'
    # cmd-shift-5           = 'move-node-to-workspace 5'
    # cmd-shift-6           = 'move-node-to-workspace 6'
    # cmd-shift-7           = 'move-node-to-workspace 7'
    # cmd-shift-8           = 'move-node-to-workspace 8'
    # cmd-shift-9           = 'move-node-to-workspace 9'

    # First row
    # cmd-shift-q       =     'move-node-to-workspace Q'                                             
    # cmd-shift-w       =     'move-node-to-workspace C'                                                                                      
    # cmd-shift-e       =     'move-node-to-workspace O'                                               
    # cmd-shift-r       =     'move-node-to-workspace P'
    # cmd-shift-t     =     'move-node-to-workspace W'                                              # attributed to closing windows
    # cmd-shift-y       =     'move-node-to-workspace J'
    # cmd-shift-u       =     'move-node-to-workspace M'
    # cmd-shift-i       =     'move-node-to-workspace D'
    # cmd-shift-o       =     'move-node-to-workspace deadKey'
    # cmd-shift-p       =     'move-node-to-workspace Y'
    
    # Second row
    # cmd-shift-a       =     'move-node-to-workspace A'
    # cmd-shift-s     =     'move-node-to-workspace S'                                               # attributed to resizing
    # cmd-shift-d       =     'move-node-to-workspace E'
    # cmd-shift-f       =     'move-node-to-workspace N'
    # cmd-shift-g       =     'move-node-to-workspace F'
    # cmd-shift-h     =     'move-node-to-workspace L'
    # cmd-shift-j     =     'move-node-to-workspace R'
    # cmd-shift-k     =     'move-node-to-workspace T'
    # cmd-shift-l     =     'move-node-to-workspace I'
    # cmd-shift-semicolon = 'move-node-to-workspace U'

    # Third row
    # cmd-shift-z       =     'move-node-to-workspace Z'
    # cmd-shift-x       =     'move-node-to-workspace X'
    # cmd-shift-c     =     'move-node-to-workspace -'
    # cmd-shift-v       =     'move-node-to-workspace V'
    # cmd-shift-b       =     'move-node-to-workspace B'
    # cmd-shift-n     =     'move-node-to-workspace .'                                               # attributed to back-and-forth
    # cmd-shift-m       =     'move-node-to-workspace H'
    # cmd-shift-comma   =     'move-node-to-workspace G'
    # cmd-shift-period =    'move-node-to-workspace ,'
    # cmd-shift-slash   =     'move-node-to-workspace K'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
cmd-enter       =     'mode service'




[[on-window-detected]]
    if.app-id         =     'com.brave.Browser'
    run               =     'move-node-to-workspace 1'

[[on-window-detected]]
    if.app-id         =     'com.mitchellh.ghostty'
    run = [
      # FIX: this is a workaround for https://github.com/nikitabobko/AeroSpace/issues/68
      # this was also observed in:
      # - https://github.com/ghostty-org/ghostty/issues/1840
      # - https://github.com/ghostty-org/ghostty/issues/2006
      "layout floating",
      "move-node-to-workspace 6",
    ]

[[on-window-detected]]
    if.app-id         =     'md.obsidian'
    run               =     'move-node-to-workspace 7'

[[on-window-detected]]
    if.app-id         =     'notion.id'
    run               =     'move-node-to-workspace 7'

[[on-window-detected]]
    if.app-id         =     'com.google.Chrome'
    run               =     'move-node-to-workspace 4'

[[on-window-detected]]
    if.app-id         =     'org.videolan.vlc'
    run               =     'move-node-to-workspace 9'

[[on-window-detected]]
    if.app-id         =     'org.qbittorrent.qBittorrent'
    run               =     'move-node-to-workspace 9'

[[on-window-detected]]
    if.app-id         =     'com.apple.Terminal'
    run               =     'move-node-to-workspace 9'

[[on-window-detected]]
    if.app-id         =     'com.apple.systempreferences'
    run               =     'move-node-to-workspace 9'

[[on-window-detected]]
    if.app-id         =     'com.apple.finder'
    run               =     'move-node-to-workspace 0'

[[on-window-detected]]
    if.app-id         =     'com.microsoft.VSCode'
    run               =     'move-node-to-workspace 5'

[[on-window-detected]]
    if.app-id         =     'dev.warp.Warp-Stable'
    run               =     'move-node-to-workspace 6'






[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

#   cmd-shift-h = ['join-with left', 'mode main']
#   cmd-shift-j = ['join-with down', 'mode main']
#   cmd-shift-k = ['join-with up', 'mode main']
#   cmd-shift-l = ['join-with right', 'mode main']

    shift-0           = ['move-node-to-workspace 0', 'workspace 0', 'mode main']
    shift-1           = ['move-node-to-workspace 1', 'workspace 1', 'mode main']
    shift-2           = ['move-node-to-workspace 2', 'workspace 2', 'mode main']
    shift-3           = ['move-node-to-workspace 3', 'workspace 3', 'mode main']
    shift-4           = ['move-node-to-workspace 4', 'workspace 4', 'mode main']
    shift-5           = ['move-node-to-workspace 5', 'workspace 5', 'mode main']
    shift-6           = ['move-node-to-workspace 6', 'workspace 6', 'mode main']
    shift-7           = ['move-node-to-workspace 7', 'workspace 7', 'mode main']
    shift-8           = ['move-node-to-workspace 8', 'workspace 8', 'mode main']
    shift-9           = ['move-node-to-workspace 9', 'workspace 9', 'mode main'] 

    # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
    # You can uncomment the following lines to open up terminal with alt + enter shortcut
    # (like in i3)
    cmd-enter = 'macos-native-fullscreen'
    cmd-shift-enter = 'layout floating tiling'

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    cmd-period        =    'layout tiles horizontal vertical'                      # , in Ergol
    cmd-shift-period  =    'layout accordion horizontal vertical'                  # , in Ergol
    cmd-t             =    'close'                                                 # w in Ergol
    cmd-shift-t       =    'close-all-windows-but-current --quit-if-last-window'   # w in Ergol

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    cmd-n             =    'focus-back-and-forth'                                  # maps to . in Ergol
    cmd-shift-n       =    'workspace-back-and-forth'                              # maps to . in Ergol

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    cmd-c             =     'move-node-to-monitor --wrap-around next'              # maps to - in Ergol
    cmd-shift-c       =     'move-workspace-to-monitor --wrap-around next'              # maps to - in Ergol

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    cmd-h             =     'focus left'
    cmd-j             =     'focus down'
    cmd-k             =     'focus up'
    cmd-l             =     'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    cmd-shift-h       =     'move left'
    cmd-shift-j       =     'move down'
    cmd-shift-k       =     'move up'
    cmd-shift-l       =     'move right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    cmd-shift-s       =     'resize smart -100'                                   # maps to s in Ergol
    cmd-s             =     'resize smart +100'                                         # maps to s in Ergol  
